/*
 * This source file was generated by the Gradle 'init' task
 */
package chapter_3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int i = 1;
        boolean b = true;
        
    
    }
}
